language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - "pip install -r requirements-dev.txt"
  - "pip install ."
script: py.test src/geventhttpclient/tests

jobs:
  include:
    - stage: build
      sudo: required
      services:
        - docker
      os: linux
      python: "3.8"
      install:
        - pip install cibuildwheel==1.3.0
      script:
        - cibuildwheel --output-dir wheelhouse
        # Build sdist distribution as well
        - python setup.py sdist -d wheelhouse
        # Upload to PyPI on tags
        - if [ "${TRAVIS_TAG:-}" != "" ]; then
            pip install twine;
            python -m twine upload --skip-existing wheelhouse/*;
          fi
      env:
        - CIBW_SKIP="cp33 cp34"
    - stage: build
      sudo: required
      os: osx
      osx_image: xcode9.4
      language: generic
      install:
        # Python 3 is needed to run cibuildwheel
        - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
            brew update;
            brew upgrade python;
          fi
        - pip3 install cibuildwheel==1.3.0
      script:
        - cibuildwheel --output-dir wheelhouse
        # Upload to PyPI on tags
        - if [ "${TRAVIS_TAG:-}" != "" ]; then
            pip install twine;
            python -m twine upload --skip-existing wheelhouse/*;
          fi
      env:
        - CIBW_SKIP="cp33 cp34"
