language: python
sudo: false
python:
  - "2.7"
  - "3.4"
install:
  - "pip install ."
script: py.test src/geventhttpclient/tests

jobs:
  include:
    - stage: build
      sudo: required
      services:
        - docker
      os:
        - linux
        - osx
      python: "3.6"
      script:
        - pip install cibuildwheel==0.6.0
        - cibuildwheel --output-dir wheelhouse

